# Generated by Django 4.0.5 on 2022-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_date_added_comment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
