# Generated by Django 4.0.5 on 2022-08-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_post_comment_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
