# Generated by Django 4.1 on 2022-08-21 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_day_remove_blogpost_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
